#!/bin/bash

# git-switchbranch
# @author shadowhand https://github.com/shadowhand
# @license MIT
#
# installation:
# save this file as git-switchbranch somewhere in your $PATH
# make it executable: chmod +x git-switchbranch
#
# optional:
# alias switchbrach to "sb": git config --global alias.sb switchbranch
#
# usage:
# git switchbranch
# select the branch you want to move to using numbers
# press enter
# ???
# profit
#
# enjoy!
#

usage() {
	echo "usage: git switchbranch"
}

version() {
    echo "switchbranch v0.0.2"
}

select_branch() {
    # Set the prompt string
    PS3="--> Select a branch? "
    # first branch is always "master"
    branches=("master $(git branch | sed -e 's/*//' -e 's/(no branch)//' -e 's/master//')")
    select selected in $branches; do
        if [ "$selected" == "quit" -o "$selected" == "q" -o "$selected" == "" ]; then
            exit 1
        fi
        git checkout "$selected"
        exit 0
    done
}

main() {
    command="$1"
    shift
    case $command in
        "version") version;;
        *) select_branch "$@";;
    esac
}

main "$@"
